<?php
/**
 * @package   ImpressPages
 */

namespace Plugin\GrooaPayment;
use Plugin\GrooaUser\Model\GrooaUser;
use Plugin\Track\Model\Track;

class AdminController
{
    /**
     * @ipSubmenu Bulk Purchases
     * Laura often gives her investors and customers to pay in bulks.
     * This fields allows her the option to add a payment to a user in bulks
     */
    public function index() {
        $config = [
            'title' => 'User Bulk Purchases',
            'table' => 'grooa_course_bulk_purchases',
            'idField' => 'id',
            'fields' => [
                [
                    'field' => 'id',
                    'label' => 'ID',
                    'allowCreate' => false,
                    'allowUpdate' => false
                ],
                [
                    'field' => 'userid',
                    'label' => 'user',
                    'type' => 'Select',
                    'values' => GrooaUser::getWithIdAndTitle()
                ],
                [
                    'field' => 'courseId',
                    'label' => 'Grooa Course',
                    'type' => 'Select',
                    'values' => Track::getGrooaCourseWithIdAndName()
                ],
                [
                    'field' => 'createdOn',
                    'label' => 'Created On',
                    'type' => 'Text',
                    'allowCreate' => false,
                    'allowUpdate' => false
                ]
            ],
            'pageSize' => 15
        ];

        return ipGridController($config);
    }

    /**
     * @ipSubmenu Single Purchases
     */
    public function singlePurchases() {
        $config = [
            'title' => 'Single Purchases',
            'table' => 'track_order',
            'idField' => 'orderId',
            'actions' => [
                [
                    'type' => 'Html',
                    'html' => '<a class="button" style="margin: auto 1em;" href="'. ipConfig()->baseUrl(). 'online-courses">To Master Class</a>'
                ],
                [
                    'type' => 'Html',
                    'html' => '<a class="button" style="margin: auto 1em;" href="'. ipConfig()->baseUrl(). '?aa=Track">Admin Master Class</a>'
                ],
                [
                    'type' => 'Html',
                    'html' => '<a class="button" style="margin: auto 1em;" href="'. ipConfig()->baseUrl(). '?aa=User">Admin Users</a>'
                ]
            ],
            'fields' => [
                [
                    'label' => 'General Data',
                    'type' => 'Tab'
                ],
                [
                    'field' => 'orderId',
                    'label' => 'id',
                    'type' => 'Integer',
                    'allowCreate' => false,
                    'allowUpdate' => false,
                    'ignoreDb' => true // Autogenerated
                ],
                [
                    'field' => 'userId',
                    'label' => 'User',
                    'type' => 'Select',
                    'values' => GrooaUser::getWithIdAndTitle()
                ],
                [
                    'field' => 'trackId',
                    'label' => 'Module',
                    'type' => 'Select',
                    'values' => Track::getWithIdAndTitle()
                ],
                [
                    'field' => 'type',
                    'label' => 'Payment Type',
                    'type' => 'Select',
                    'note' => 'Manual= User har payed through invoice (Just use this), PayPal= User has used to PayPal button',
                    'values' => [
                        ['manual', 'Manual'],
                        ['paypal', 'PayPal']

                    ]
                ],
                [
                    'label' => 'Generated Data',
                    'type' => 'Tab'
                ],
                [
                    'field' => 'createdOn',
                    'label' => 'Created on',
                    'ignoreDb' => true // Autogenerated
                ],
                [
                    'field' => 'payerId',
                    'label' => 'payerID',
                    'type' => 'Text',
                    'hint' => "PayPal's Id for the payer"
                ],
                [
                    'field' => 'paymentId',
                    'label' => 'paymentID',
                    'type' => 'Text',
                    'hint' => "PayPal's Id for the created payment"
                ],
                [
                    'field' => 'saleId',
                    'label' => 'saleID',
                    'type' => 'Text',
                    'hint' => "PayPal's Id for the executed sale"
                ],
                [
                    'field' => 'state',
                    'label' => 'Payment State',
                    'type' => 'Select',
                    'default' => 'none',
                    'values' => [
                        'none',
                        'pending',
                        'canceled',
                        'completed',
                        'rejected'
                    ]
                ],
                [
                    'field' => 'completed',
                    'label' => 'Completed',
                    'type' => 'Text',
                    'default' => null
                ],
                [
                    'field' => 'paymentExecuted',
                    'label' => 'Payment Executed',
                    'type' => 'Text',
                    'default' => null,
                    'hint' => 'DateTime when payment has been executed (with state pending)'
                ],
                [
                    'field' => 'invoiceNumber',
                    'label' => 'Invoice Number',
                    'type' => 'Text',
                    'ignoreDb' => true
                ],
                [
                    'label' => 'Override Options',
                    'type' => 'Tab'
                ],
                [
                    'field' => 'override',
                    'label' => 'Manual override purchase',
                    'type' => 'Checkbox'
                ],
                [
                    'field' => 'overrideReason',
                    'label' => 'Reason for override',
                    'type' => 'RichText'
                ],
                [
                    'field' => 'overridePrice',
                    'label' => 'Amount Payed',
                    'type' => 'Text',
                    'default' => 0.0
                ]
            ],
            'createFilter' => function ($post) {
//                die(json_encode($post));
                $post = AdminController::addValuesIfManual($post);

                return $post;
            },
            'pageSize' => 15
        ];

        return ipGridController($config);
    }


    private static function addValuesIfManual($post) {

        if ($post['type'] == 'manual') {
            $now = date("Y-m-d H:i:s");
            $uniqid = uniqid('grooa-');

            $post['createdOn'] = $now;
            $post['paymentExecuted'] = $now;
            $post['completed'] = $now;

            $post['state'] = 'completed';

            $post['invoiceNumber'] = $uniqid;
            $post['paymentId'] = $uniqid;
            $post['payerId'] = $uniqid;
            $post['saleId'] = $uniqid;

            $post['override'] = true;
        }

        return $post;
    }
}